### PR TITLE
new it.json file

### LINKED ISSUE #7: drevo tryfing 2 italian 105 key - some keys are not changing color
Hello. I own a drevo tryfing 2 but the 105 keys italian version,

I have note d that some keys are no modified, so I have copied the fr configuration, and modified to make an italian version:
This is working 

```
# it locale
if 'it' in locale.setlocale(locale.LC_ALL, ''):
    itkeys = {'ù': 0x32,
              '<': 0x64}
    keys.update(itkeys)

```

Same problem with all the keypad keys

```
        #
        'kpnlk': 0x53, 'kpdiv': 0x54, 'kpmul': 0x55, 'kpsub': 0x56,
        'kpadd': 0x57, 'kpent': 0x58, 'kpdot': 0x63,
        #
        'kp1': 0x59, 'kp2': 0x5A,'kp3': 0x5B,'kp4': 0x5C,'kp5': 0x5D,
        'kp6': 0x5E, 'kp7': 0x5F, 'kp8': 0x60, 'kp9': 0x61,
        'kp0': 0x62
```

and in the "key groups", i've added some definition:

```
                             'del', 'end', 'p-down']
                 'kp_digits': ['kp1', 'kp2','kp3','kp4','kp5',
                    'kp6','kp7', 'kp8', 'kp9', 'kp0' ],
                 'kp_oper': ['kpnlk', 'kpdiv','kpmul', 'kpsub',
                      'kpadd', 'kpent','kpdot']

```

I have this setting in .dtv2change file

```
{"kbd": "cyan"}
```
and everything now works

Regards

carlo D.

### PR DESCRIPTION
**Pull request by onekk**
Added the two keys missing, it's a mess to determine the order, so I've added them near similar numbers, 0x32 after 0x31 and 0x64 to the end of file.

Hope it is enough, I leave to you to modify the main interface code.

How to add the keypad keys, or better, i could add them to the it.json file or you prefer something different?

Regards

Carlo D.

### CODE REVIEW

**Comment by cobacdavid** [comment]
Hi Carlo,
I think I can merge this PR. And you possibly can open another one to add to all json files the keypad keys as it seems to be OK for TKL version of the keyboard.

Furthermore, I was wondering about restructuring json files and creating dictionary keys: '1st row', '2nd row" etc. to create entry points in these files. Additionally this will create categories in keys colors management.

**Comment by onekk** [comment]
Yes restructuring key order to show the row will be a goo idea.

Do you have a some hint about retrieving key vaule associated with usb hid "codes" in amore automate way, I suspect that some keys have to be reorganised also for italian keyboard, as colors are correct, but maybe referring with a "keycode" will change the wrong key as some keys position are different. Italian Layout generally use letters like US ASCII (although old typewriters have QZERTY instead of QWERTY layout.) but for other things, like parentesis and punctation signs. this is not every time true.

regards

Carlo D.

**Comment by cobacdavid** [comment]
I just have searched to answer your question. I found these  documents:
 - [usb hid specs](https://usb.org/sites/default/files/hut1_21.pdf#page=83) which specifies key id but there's an important note on foreign languages...
 - [common keyboard layouts](https://www.w3.org/TR/uievents-code/#keyboard-common-layouts) where I can see "offical" names for categories and rows... is this really "official" or usual? I guess I should change for these category names in dtv2.
 - [SE answer to your specific question](https://superuser.com/questions/550858/how-to-get-usb-hid-id-of-pressed-keyboard-keys) The first answer provides a convenient way to get your keys id (it worked correctly on my Debian 10 based OS).

**Comment by cobacdavid** [comment]
@onekk I just changed json files structure: can you, please, modify `it.json` file for it corresponds to this structure.
Actually, I'm sure of `fr.json` but I also changed `en.json` that I cannot checked... so I prefer you change yourself `it.json`
Thx

**Pull request merged**
