### PR TITLE
new work on json

### PR DESCRIPTION
**Pull request by onekk**
This seem to be anew version, sorry for the other file in the commit.

How i could test row by row the colors, so I could check if all is working right?

How to add the keypad codes in this new scheme?

Regards

Carlo D

### CODE REVIEW

**Comment by cobacdavid** [comment]
Hi Carlo,
have a look at [this example in examples section](https://github.com/cobacdavid/dtv2/blob/master/examples/dtv2reader/config_parallels.json)

**Comment by cobacdavid** [comment]
> How to add the keypad codes in this new scheme?

I think keypad keys should be distributed according to their alignment with alphanumeric rows.
In complement, a new category `numpad` should be declared in `category_keys` dictionary inside `dtv2.py`.

**Comment by onekk** [comment]
Seems that something wrong is happening with the configuration file you linked me

```
Traceback (most recent call last):
  File "/home/carlo-arch/.local/bin/dtv2change", line 64, in <module>
    apply_changes(clavier, dico_config)
  File "/home/carlo-arch/.local/bin/dtv2change", line 43, in apply_changes
    kbd.category(k, colour.COLOR_NAME_TO_RGB[v])
KeyError: '#ff0'

```

Maybe putting color names instead of codes will solve problem, but how to find a list of accepted colour names by the colour package.

EDIT: it seems that the key 'ù' 0x32 code is not changing with the correct row bu with the upper row, strange enough, I've found that **evtest** will show the kay codes, but it obviously show use orginal "US" names.


Regards

Carlo D.

**Comment by cobacdavid** [comment]
Did you use the last `dtv2change` version? I added, in the latest version, the possibility to manage usual hex colors definition.

For the `ù` key, is it only with yout `it` config?

**Comment by onekk** [comment]
Seems that I have used the latest as I've synced my repo with yours prior to make the it,json file.

Sadly there is no -V option on the script that print the version to check for come conflicts, but launching the script from local git repo (my working version gave same result)

for the rest, as I don't know how to address the localized key using a python scripts, as dtv2 library didn't permit to load the localized json file, each key different from English version is not addressable with python script, as it will be a good way to test things and maybe put in place a set of test to make maybe some other localization more easy.

Regards

Carlo D.

**Comment by cobacdavid** [comment]
Oh sorry Carlo, you're absolutely right: I changed `dtv2reader` but still not `dtv2change`. So it's `dtv2reader` which actually handle hex colors...

As you said, I should add some property to dtv2 object so it is possible to ease localisation change.

**Comment by cobacdavid** [comment]
I made some changes:
 - all code in `dtv2`class
 - add a `local` property so localisation can be changed according to an existing `json` file
 - change `dtv2change` so something like `$ dtv2change -cat "row A" "#f0f"` works
 - add a `-V` option for both executables showing last modified date. But I've to improve argument parsing (I should read the doc...)

**Comment by onekk** [comment]
Hi Davis, many thanks, I will try to catch the strange ù behaviour, I coudl think that also 

```
            'letters': string.ascii_lowercase,
```

Will have some problems at least for "non ascii" language like thos with accented letters, they "òàùèì" at least for italian are letters but are not taken in account in ascii_lowercase that returns:

```
abcdefghijklmnopqrstuvwxyz
```

I'm doing some more test to catch the problem but **evtest** is returning:

```
Event: time 1622448235.650609, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70032
Event: time 1622448235.650609, type 1 (EV_KEY), code 43 (KEY_BACKSLASH), value 1
Event: time 1622448235.650609, -------------- SYN_REPORT ------------
Event: time 1622448235.715567, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70032
Event: time 1622448235.715567, type 1 (EV_KEY), code 43 (KEY_BACKSLASH), value 0 
```
  
So the scan code is correctly 0x32 (i don0t know why it is reported as 70032) but it correspond (it seems that it reports the "key press" and the "key release" event) and the EV_KEY is the BACKSLASH of an ascii keyboard, so no surprise from this side of problem.

Regards

Carlo D.

**Comment by onekk** [comment]
Hello, I've done some works, 

json file is update and tested, at least for italian, Iìhave used this tricks:

```
import time
import string

my_kbd = dtv2.dtv2()

my_kbd.local = "it"

rows = ()

#rows += ('esc','f1','f2','f3','f4','f5','f6','f7','f8','f9','f10', 'f11', 'f12', 'PS', 'SL', 'PB')

#rows += ('\\','1','2','3','4','5','6','7','8','9','0', "'", 'ì', 'BACKS', 'ins', 'home', 'p-up', 'kpnlk', 'kpdiv', 'kpmul', 'kpsub')

#rows += ('tab','q','w','e','r','t','y','u','i','o','p', 'è', '+', 'del', 'end', 'p-down', 'kp7', 'kp8', 'kp9', 'kpadd')

#rows += ('caps','a','s','d','f','g','h','j','k','l','ò', 'à', 'ù', 'kp4', 'kp5', 'kp6')

#rows += ('lshift','<','z','x','c','v','b','n','m',',','.', '-', 'rshift', 'up', 'kp1', 'kp2', 'kp3')

#rows += ('lctrl','win','lalt','space','ralt','FN','compo','rctrl','left','down','right', 'kp0', 'kpdot', 'kpent')


for key in rows:
    print(key)
    my_kbd.key(key, (255, 0, 0))
    time.sleep(0.25)
    my_kbd.key(key, (0,255,255))

```
And it seems to work, I've noted some error in defining the "," "." wrongly as ";" and ":" and corrected.

have added a .gitignore file to exclude __pycache__ and .pyc and so on, a bare minimal thing.

One question?

There is a method when testing the keyboard with the above code, that highlight in red one key at a time using the row, to read the color of the key and restore it after having "highlight" it?

Hope it helps.

TIA and Regards

Carlo D.

**Comment by cobacdavid** [comment]
I'm going to merge your PR.
Great job, Carlo!

May be we should create a new directory containing tricks like yours, and `evtest` testing or maybe have this in the documentation...

**Comment by onekk** [comment]
Yes it is a good idea, maybe it will be useful:

two other things:

1) do you agree with keypad names, usually they have "kp_"  prefix, but I've followed the style of names, as they are normal keys I don't want to use ALLCAPS notation

2) for some categories, maybe kbdigits and kbsymbols to group numbers and other symbols, even if 'kbnlk' for could be put in another categories, maybe with "tab", "caps", "BACKS" and "ent" like in some keyboard color shemes see maybe:

https://en.wikipedia.org/wiki/Space-cadet_keyboard

on the bottom there are some functional grouping of keys.

It will be a technical separation maybe useful for someone.

Regards

Carlo D.

**Comment by cobacdavid** [comment]
@onekk Could you cut/copy your previous message and open a issue maybe labeled with "enhancement", please?
As this PR is now closed, I think you open interesting suggestions here. I was wondering about creating possible aliases for keys allowing user to easily find each key name.
And also you're right: add some more categories will be useful.

**Pull request merged**
